### ISSUE TITLE
训练集路径问题

### ISSUE THREAD

**Issue by DRRNO** [zychen-ustc/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors#20]
运行主程序后，会出现Traceback (most recent call last):
  File "G:/桌面/PSD/PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors-main/PSD/main.py", line 45, in <module>
    train_data_loader = DataLoader(TrainData(crop_size, train_data_dir), batch_size=train_batch_size, shuffle=True,
  File "G:\桌面\PSD\PSD-Principled-Synthetic-to-Real-Dehazing-Guided-by-Physical-Priors-main\PSD\datasets\pretrain_datasets.py", line 20, in __init__
    self.haze_names = list(os.walk(self.haze_dir))[0][2]
IndexError: list index out of range
下面是我的训练集路径
val_data_dir = 'G:/桌面/数据集/SOTS(1)/SOTS/outdoor/'
train_data_dir = 'G:/桌面/数据集/OTS_ALPHA/'
为什么会显示超出范围呢

**Comment by zychen-ustc** [comment]
您好！可能是因为os.walk对子文件夹的排布有所要求。以val_data_dir为例，如果outdoor文件夹下就是图片文件，可以尝试用self.haze_names = os.listdir(val_data_dir)这个语句。
